import type { Metadata } from "next";
import { JetBrains_Mono, Space_Grotesk } from "next/font/google";
import Link from "next/link";

import SafeModeToggle from "@/components/custom/safe-mode-toggle";
import ThemeToggle from "@/components/custom/theme-toggle";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-stitch-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-stitch-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-dvh min-h-0 overflow-hidden antialiased",
        spaceGrotesk.variable,
        jetbrainsMono.variable,
      )}
    >
      <body className="flex h-dvh min-h-0 max-h-dvh flex-col overflow-hidden font-sans">
        <ThemeProvider>
          <nav className="shrink-0 border-b">
            <div className="max-w-[1440px] mx-auto w-full px-4 py-2 flex justify-between items-center">
              <Link
                href="/"
                className="font-bold text-4xl hover:text-primary transition-colors"
              >
                GhostFile
                <span className="text-sm text-muted-foreground ml-2">
                  v.1.0.0
                </span>
              </Link>
              <div className="flex items-center gap-2 sm:gap-3">
                <ThemeToggle />
                <SafeModeToggle />
              </div>
            </div>
          </nav>
          <main className="flex min-h-0 flex-1 basis-0 flex-col overflow-hidden">
            {children}
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
