import type { Metadata } from "next";
import { JetBrains_Mono, Space_Grotesk } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import Link from "next/link";
import SafeModeToggle from "@/components/custom/safe-mode-toggle";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-stitch-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-stitch-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "dark",
        "h-full antialiased",
        spaceGrotesk.variable,
        jetbrainsMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col font-sans">
        <nav className="border-b">
          <div className="max-w-[1440px] mx-auto w-full px-4 py-2 flex justify-between items-center">
            <Link
              href="/"
              className="font-bold text-4xl hover:text-primary transition-colors"
            >
              GhostFile
              <span className="text-sm text-muted-foreground ml-2">
                v.1.0.0
              </span>
            </Link>
            <SafeModeToggle />
          </div>
        </nav>
        <main className="flex-1 flex">{children}</main>
      </body>
    </html>
  );
}
